fitter: "lm"

psf_ntry: 2
obj_ntry: 2
psf_model: "em2"
region: "seg_and_sky"

# in arcsec
psf_offset_max: 0.25

reject_outliers: True

use_cenprior: True
cen_width: 0.27

gprior_type: null

fit_types: ['psf','simple','cmodel','match']
reject_outliers: True

gprior_type: null
#gprior_type: "exp"
#gprior_pars: [27.63, 1.25, 0.016, 0.77]
