# for testing only: match on self
# no prior on center
fitter: "lm"

psf_ntry: 2
obj_ntry: 2
psf_model: "em2"
region: "seg_and_sky"

# in arcsec
psf_offset_max: 0.25

match_use_band_center: False
match_self: True
max_box_size: 96

fit_types: ['psf','simple','cmodel','match']
reject_outliers: True

use_cenprior: True
cen_width: 0.27

#gprior_type: null
gprior_type: "exp"
gprior_pars: [27.63, 1.25, 0.016, 0.77]
