fitter: "mcmc"

psf_model: "em2"
psf_ntry: 2

# in arcsec
psf_offset_max: 0.25


nwalkers: 20
nstep: 200
burnin: 400
#nwalkers: 100
#nstep: 200
#burnin: 200

match_nwalkers: 20
match_burnin: 100
match_nstep:  100
#match_nstep:  200

do_pqr: False
mca_a: 3.0

region: "seg_and_sky"

cen_width: 0.27

gprior_type: "exp"
gprior_pars: [27.63, 1.25, 0.016, 0.77]
when_prior: "after"


# need both these for cmodel
simple_models: ['exp']

match_self: True
max_box_size: 256

#fit_types: ['psf','simple','cmodel','match']
fit_types: ['psf','simple','match']

make_plots: True
prompt: False

reject_outliers: True
