fitter: "mcmc"

psf_model: "em2"
psf_ntry: 2

# in arcsec
psf_offset_max: 0.25


#nwalkers: 20
nwalkers: 80
nstep: 200
burnin: 400

do_pqr: False
mca_a: 3.0

region: "seg_and_sky"

cen_width: 0.27

gprior_type: "flat"

# need both these for cmodel
simple_models: ['exp','dev']
