fitter: "ngmix"

nwalkers: 80
burnin: 400
nstep: 800
mca_a: 2.0

# if we burn in from coadd
guess_burnin: 400
guess_nstep: 800

# Mike has used a single gaussian PSF
psf_em_pars:
    ngauss: 1
    ntry: 30
    maxiter: 5000
    tol: 5.0e-6

# always fit 1 gauss
# don't need to nail this, set tol lower
galaxy_em_pars:
    tol: 5.0e-4
    maxiter: 5000
    ntry: 30


# at least one band must have s/n > this or
# we won't fit the slow mcmc 
min_em1_s2n: 4

#region: "seg_and_sky"
region: "cweight-nearest"

# in arcsec
psf_offset_max: 0.25

max_box_size: 192

# in addition to em 1gauss and a psf flux
fit_models: ['exp']

do_shear: True

reject_outliers: True

use_cen_prior: True
cen_width: 0.27

# from fitting to all cosmos galaxies in galsim data
g_prior_types: ["cosmos-sersic"]
g_prior_during: True

# still want true here even if using the coadd guess,
# in case the guess is broken
draw_g_prior: True

T_prior_types: ["flat"]
#T_prior_pars: [ [0.0001,3000.0] ]
# natural log
T_prior_pars: [ [-9.21034037,  8.00636757] ]

# some objects have absolutely crazy flux values
counts_prior_types: ["flat"]
#counts_prior_pars: [ [0.0001,100000.0] ]
# natural log
counts_prior_pars: [ [ -9.21034037,  11.51292546] ]

# over-rides draw_g_prior for the multi-epoch
guess_from_coadd: False

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

checkpoints: [30,60,110]

debug: 0
