fitter: "ngmix"

nwalkers: 20
burnin: 400
nstep: 200
mca_a: 3.0

psf_ntry: 3
psf_model: "em2"
psf_maxiter: 500
psf_tol: 5.0e-4

# at least one band must have psf s/n > this
# we won't fit other models if the s/n is too low
# this might be tweaked depending on how many bands
# and images you have in the stack.
min_psf_s2n: 4

region: "seg_and_sky"

# in arcsec
psf_offset_max: 0.25

max_box_size: 256

fit_types: ['psf','simple']

simple_models: ['exp','dev']
do_pqr: False
do_lensfit: True

reject_outliers: True

use_cen_prior: True
cen_width: 0.27

g_prior_type: "ba"
g_prior_pars: 0.3
#g_prior_type: "exp"
#g_prior_pars: [27.63, 1.25, 0.016, 0.77]
draw_g_prior: True


# checkpoint time in seconds, needed for condor in case we pass
# a batch system limit such as in the condor scavenge
#
# 1.5 hours


checkpoint: 5400

make_plots: False
debug: 0
