# 2 gauss psf
fitter: "ngmix"
fitter_class: "coadd-only"
fit_me_galaxy: False

nu: 0.0

max_box_size: 192

# using same as 008 here.  maybe more steps fewer walkers better in a way
# since they are independent
emcee_a: 2.0
emcee_nwalkers: 80
emcee_burnin: 800
emcee_nstep: 800

psf_em_pars:
    ngauss: 2
    ntry: 20
    maxiter: 5000
    tol: 5.0e-6

# at least one band must have s/n > this or
# we won't fit the slow mcmc 
min_psf_s2n: 4

#region: "seg_and_sky"
region: "cweight-nearest"

# in arcsec
psf_offset_max: 0.25

# in addition to gauss fit on coadd and a psf flux
fit_models: ['exp']

# for now only
do_shear: False

use_cen_prior: True
cen_width: 0.27

# from fitting to all cosmos galaxies in galsim data
#g_prior_types: ["flat"]
g_prior_types: ["cosmos-sersic"]


# 1.0e+06 is about 700 arcsec, 2600 pixels
T_prior_types: ["TwoSidedErf"]
T_prior_pars: [ [-0.07, 0.03, 1.0e+06, 1.0e+05] ]

counts_prior_types: ["TwoSidedErf"]
counts_prior_pars: [ [-1.0, 0.1, 1.0e+09, 0.25e+08] ]

# this means repeat the above for each band
counts_prior_repeat: True

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

checkpoints: [0,30,60,110]
