fitter: "ngmix"

nwalkers: 80
burnin: 400
nstep: 800
mca_a: 2.0

psf_em_pars:
    ngauss: 3
    ntry: 2000
    maxiter: 50000
    tol: 5.0e-6

# always fit 1 gauss
# don't need to nail this, set tol lower. also need fewer ntry since
# should easily converge to this low tol
#galaxy_em_pars:
#    ntry: 200
#    tol: 5.0e-4
#    maxiter: 5000


# at least one band must have s/n > this or
# we won't fit the slow mcmc 
min_psf_s2n: 4

#region: "seg_and_sky"
region: "cweight-nearest"

# in arcsec
psf_offset_max: 0.25

max_box_size: 192

# in addition to gauss fit on coadd and a psf flux
fit_models: ['exp','dev']

do_shear: True

reject_outliers: True

# note the coadd_gauss fit will share the priors with the first one
# of these

use_cen_prior: True
cen_width: 0.27

# from fitting to all cosmos galaxies in galsim data
g_prior_types: ["cosmos-sersic","cosmos-sersic"]

# log10
T_prior_types: ["flat","flat"]
T_prior_pars: [ [-5.0, 3.5],[-5.0, 3.5] ]

counts_prior_types: ["flat","flat"]
counts_prior_pars: [ [-4.0,6.5],[-4.0,6.5] ]
# this means repeat the above for each band
counts_prior_repeat: True

guess_type: 'coadd'

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

checkpoints: [30,60,110]
